// Generated from: test/features/business-messaging.feature
import { test } from "../../../test/features/steps/fixtures.js";

test.describe('Consolidated View Business Messages page', () => {

  test('Message data updates correctly once a contact is selected.', { tag: ['@basic', '@possible-vi-test', '@working'] }, async ({ Given, When, Then, And, businessMessagingPage, page }) => { 
    await Given('I have gone to the \'Business Messages\' page', null, { page }); 
    await And('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I select a contact', null, { businessMessagingPage }); 
    await And('I select the Date Range field as \'Last 36 months\'', null, { businessMessagingPage }); 
    await When('I select the first message', null, { businessMessagingPage }); 
    await Then('the right-hand pane updates with a bold title, a Date field, a Read field, a Deleted field and a Message field', null, { businessMessagingPage }); 
    await And('there is a label in the right-hand pane \'Links in the message below do not work\'', null, { businessMessagingPage }); 
  });

  test('Message data updates correctly after another contact is selected.', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected the contact \'Vilma Yundt\'', null, { businessMessagingPage }); 
    await When('I select the message with the subject \'Agnosco cohaero ancilla.  \'', null, { businessMessagingPage }); 
    await Then('right-hand pane updates with the following information', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Title"},{"value":"Agnosco cohaero ancilla."}]},{"cells":[{"value":"Date"},{"value":"1723577035401"}]},{"cells":[{"value":"Read?"},{"value":"No"}]},{"cells":[{"value":"Deleted?"},{"value":"No"}]},{"cells":[{"value":"Message"},{"value":"<p>Talis cubicularis thesis cohors venia deleo tam claudeo.</p>"}]}]}}, { businessMessagingPage }); 
  });

  test('Correct message is displayed when a contact has no messages for that business', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1106552449\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I have selected the contact \'Duncan Peacock\'', null, { businessMessagingPage }); 
    await Then('I see the \'Messages\' table is empty', null, { page }); 
    await And('I see a warning message \'There are no messages to display\' under the \'Messages\' table', null, { page }); 
  });

  test('Contacts list is empty when a business has no contacts', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1000000000\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('the Contacts drop-down is empty', null, { businessMessagingPage }); 
  });

  test('Searching for a partially matching string in the Subject column filters correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected the contact \'Vilma Yundt\'', null, { businessMessagingPage }); 
    await When('I enter \'anci\' in the search box', null, { page }); 
    await Then('I see the the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Unread"}]},{"cells":[{"value":"Date"},{"value":"1723577035401"}]},{"cells":[{"value":"Subject"},{"value":"\"Agnosco cohaero ancilla.\""}]}]}}, { businessMessagingPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Unread, Unread, Read, Unread"}]},{"cells":[{"value":"Date"},{"value":"1723577035401, 1717810388400, 1700229203688, 1726822799905"}]},{"cells":[{"value":"Subject"},{"value":"\"Agnosco cohaero ancilla.\", \"Vivo quae ultra caste.\", \"Triumphus facilis aiunt.\", \"Facilis beatae vesper copia velit.\""}]}]}}, { businessMessagingPage }); 
  });

  test('The list of contacts is correct.', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('the Contacts drop-down contains entries for \'Lauren Sanford,Terry Swaniawski,Murray Kihn,Meaghan Torp,Kristy Stiedemann,Juwan Hahn,Rod Quitzon-Gibson,Stacey Willms,Marco Kovacek,Frederic Koch-Cassin,Nayeli Kub,Vilma Yundt,Henri Weissnat,Mara Stark,Kellie Flatley\'', null, { businessMessagingPage }); 
  });

  test('The message date filter works correctly.', { tag: ['@advanced', '@data-dependent', '@this-test-will-break-as-dates-get-out-of-sync', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1106552449\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected the contact \'Catherine Pallister\'', null, { businessMessagingPage }); 
    await When('I select the Date Range field as \'Last 12 months\'', null, { businessMessagingPage }); 
    await Then('I see the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Read"}]},{"cells":[{"value":"Date"},{"value":"31/12/2025"}]},{"cells":[{"value":"Subject"},{"value":"\"Payment credit applied\""}]}]}}, { businessMessagingPage }); 
    await When('I select the Date Range field as \'Last 24 months\'', null, { businessMessagingPage }); 
    await Then('I see the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Read, Read"}]},{"cells":[{"value":"Date"},{"value":"31/12/2025, 31/12/2024"}]},{"cells":[{"value":"Subject"},{"value":"\"Payment credit applied\", \"Document approved\""}]}]}}, { businessMessagingPage }); 
    await When('I select the Date Range field as \'Last 36 months\'', null, { businessMessagingPage }); 
    await Then('I see the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Read, Read, Read"}]},{"cells":[{"value":"Date"},{"value":"31/12/2025, 31/12/2024, 31/12/2023"}]},{"cells":[{"value":"Subject"},{"value":"\"Payment credit applied\", \"Document approved\", \"Document rejected\""}]}]}}, { businessMessagingPage }); 
    await When('I select the Date Range field as \'All\'', null, { businessMessagingPage }); 
    await Then('I see the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Read, Read, Read, Unread"}]},{"cells":[{"value":"Date"},{"value":"31/12/2025, 31/12/2024, 31/12/2023, 10/02/2009"}]},{"cells":[{"value":"Subject"},{"value":"\"Payment credit applied\", \"Document approved\", \"Document rejected\", \"Document review\""}]}]}}, { businessMessagingPage }); 
  });

  test('The Read-Unread message filter works correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected the contact \'Vilma Yundt\'', null, { businessMessagingPage }); 
    await When('I select \'Read\' from the Read-Unread filter', null, { businessMessagingPage }); 
    await Then('I see the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Read"}]},{"cells":[{"value":"Date"},{"value":"1700229203688"}]},{"cells":[{"value":"Subject"},{"value":"\"Triumphus facilis aiunt.\""}]}]}}, { businessMessagingPage }); 
    await When('I select \'Unread\' from the Read-Unread filter', null, { businessMessagingPage }); 
    await Then('I see the correct list of messages as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Status"},{"value":"Unread, Unread, Unread"}]},{"cells":[{"value":"Date"},{"value":"1723577035401, 1717810388400, 1726822799905"}]},{"cells":[{"value":"Subject"},{"value":"\"Agnosco cohaero ancilla.\", \"Vivo quae ultra caste.\", \"Facilis beatae vesper copia velit.\""}]}]}}, { businessMessagingPage }); 
  });

  test('Deleted message data displays correctly', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Business Messages page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected the contact \'Vilma Yundt\'', null, { businessMessagingPage }); 
    await When('I select the message with the subject \'THIS IS NOT CURRENTLY AVAILABLE\'', null, { businessMessagingPage }); 
    await Then('the Deleted field is \'true\'', null, { businessMessagingPage }); 
    await When('I select the message with the subject \'Agnosco cohaero ancilla.  \'', null, { businessMessagingPage }); 
    await Then('the Deleted field is \'false\'', null, { businessMessagingPage }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('test/features/business-messaging.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":6,"pickleLine":4,"tags":["@basic","@possible-vi-test","@working"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Business Messages' page","stepMatchArguments":[{"group":{"start":20,"value":"Business Messages","children":[]}}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"And I select a contact","stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And I select the Date Range field as 'Last 36 months'","stepMatchArguments":[{"group":{"start":34,"value":"Last 36 months","children":[]}}]},{"pwStepLine":11,"gherkinStepLine":9,"keywordType":"Action","textWithKeyword":"When I select the first message","stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then the right-hand pane updates with a bold title, a Date field, a Read field, a Deleted field and a Message field","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":11,"keywordType":"Outcome","textWithKeyword":"And there is a label in the right-hand pane 'Links in the message below do not work'","stepMatchArguments":[{"group":{"start":41,"value":"Links in the message below do not work","children":[]}}]}]},
  {"pwTestLine":16,"pickleLine":14,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":17,"gherkinStepLine":15,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":18,"gherkinStepLine":16,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":19,"gherkinStepLine":17,"keywordType":"Context","textWithKeyword":"And I have selected the contact 'Vilma Yundt'","stepMatchArguments":[{"group":{"start":29,"value":"Vilma Yundt","children":[]}}]},{"pwStepLine":20,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When I select the message with the subject 'Agnosco cohaero ancilla.  '","stepMatchArguments":[{"group":{"start":39,"value":"Agnosco cohaero ancilla.  ","children":[]}}]},{"pwStepLine":21,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then right-hand pane updates with the following information","stepMatchArguments":[]}]},
  {"pwTestLine":24,"pickleLine":28,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":25,"gherkinStepLine":29,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1106552449'","stepMatchArguments":[{"group":{"start":39,"value":"1106552449","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":26,"gherkinStepLine":30,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":27,"gherkinStepLine":31,"keywordType":"Action","textWithKeyword":"When I have selected the contact 'Duncan Peacock'","stepMatchArguments":[{"group":{"start":29,"value":"Duncan Peacock","children":[]}}]},{"pwStepLine":28,"gherkinStepLine":32,"keywordType":"Outcome","textWithKeyword":"Then I see the 'Messages' table is empty","stepMatchArguments":[{"group":{"start":11,"value":"Messages","children":[]}}]},{"pwStepLine":29,"gherkinStepLine":33,"keywordType":"Outcome","textWithKeyword":"And I see a warning message 'There are no messages to display' under the 'Messages' table","stepMatchArguments":[{"group":{"start":25,"value":"There are no messages to display","children":[]}},{"group":{"start":70,"value":"Messages","children":[]}}]}]},
  {"pwTestLine":32,"pickleLine":36,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":33,"gherkinStepLine":37,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1000000000'","stepMatchArguments":[{"group":{"start":39,"value":"1000000000","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":34,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":35,"gherkinStepLine":39,"keywordType":"Outcome","textWithKeyword":"Then the Contacts drop-down is empty","stepMatchArguments":[]}]},
  {"pwTestLine":38,"pickleLine":42,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":39,"gherkinStepLine":43,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":40,"gherkinStepLine":44,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":41,"gherkinStepLine":45,"keywordType":"Context","textWithKeyword":"And I have selected the contact 'Vilma Yundt'","stepMatchArguments":[{"group":{"start":29,"value":"Vilma Yundt","children":[]}}]},{"pwStepLine":42,"gherkinStepLine":46,"keywordType":"Action","textWithKeyword":"When I enter 'anci' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"anci","children":[]}}]},{"pwStepLine":43,"gherkinStepLine":47,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of messages as follows","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":52,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":45,"gherkinStepLine":53,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":54,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of messages as follows","stepMatchArguments":[]}]},
  {"pwTestLine":49,"pickleLine":61,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":50,"gherkinStepLine":62,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":51,"gherkinStepLine":63,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":52,"gherkinStepLine":64,"keywordType":"Outcome","textWithKeyword":"Then the Contacts drop-down contains entries for 'Lauren Sanford,Terry Swaniawski,Murray Kihn,Meaghan Torp,Kristy Stiedemann,Juwan Hahn,Rod Quitzon-Gibson,Stacey Willms,Marco Kovacek,Frederic Koch-Cassin,Nayeli Kub,Vilma Yundt,Henri Weissnat,Mara Stark,Kellie Flatley'","stepMatchArguments":[{"group":{"start":45,"value":"Lauren Sanford,Terry Swaniawski,Murray Kihn,Meaghan Torp,Kristy Stiedemann,Juwan Hahn,Rod Quitzon-Gibson,Stacey Willms,Marco Kovacek,Frederic Koch-Cassin,Nayeli Kub,Vilma Yundt,Henri Weissnat,Mara Stark,Kellie Flatley","children":[]}}]}]},
  {"pwTestLine":55,"pickleLine":67,"tags":["@advanced","@data-dependent","@this-test-will-break-as-dates-get-out-of-sync","@require-mock-update"],"steps":[{"pwStepLine":56,"gherkinStepLine":68,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1106552449'","stepMatchArguments":[{"group":{"start":39,"value":"1106552449","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":57,"gherkinStepLine":69,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":58,"gherkinStepLine":70,"keywordType":"Context","textWithKeyword":"And I have selected the contact 'Catherine Pallister'","stepMatchArguments":[{"group":{"start":29,"value":"Catherine Pallister","children":[]}}]},{"pwStepLine":59,"gherkinStepLine":71,"keywordType":"Action","textWithKeyword":"When I select the Date Range field as 'Last 12 months'","stepMatchArguments":[{"group":{"start":34,"value":"Last 12 months","children":[]}}]},{"pwStepLine":60,"gherkinStepLine":72,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of messages as follows","stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":77,"keywordType":"Action","textWithKeyword":"When I select the Date Range field as 'Last 24 months'","stepMatchArguments":[{"group":{"start":34,"value":"Last 24 months","children":[]}}]},{"pwStepLine":62,"gherkinStepLine":78,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of messages as follows","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":83,"keywordType":"Action","textWithKeyword":"When I select the Date Range field as 'Last 36 months'","stepMatchArguments":[{"group":{"start":34,"value":"Last 36 months","children":[]}}]},{"pwStepLine":64,"gherkinStepLine":84,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of messages as follows","stepMatchArguments":[]},{"pwStepLine":65,"gherkinStepLine":89,"keywordType":"Action","textWithKeyword":"When I select the Date Range field as 'All'","stepMatchArguments":[{"group":{"start":34,"value":"All","children":[]}}]},{"pwStepLine":66,"gherkinStepLine":90,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of messages as follows","stepMatchArguments":[]}]},
  {"pwTestLine":69,"pickleLine":97,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":70,"gherkinStepLine":98,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":71,"gherkinStepLine":99,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":72,"gherkinStepLine":100,"keywordType":"Context","textWithKeyword":"And I have selected the contact 'Vilma Yundt'","stepMatchArguments":[{"group":{"start":29,"value":"Vilma Yundt","children":[]}}]},{"pwStepLine":73,"gherkinStepLine":101,"keywordType":"Action","textWithKeyword":"When I select 'Read' from the Read-Unread filter","stepMatchArguments":[{"group":{"start":10,"value":"Read","children":[]}}]},{"pwStepLine":74,"gherkinStepLine":102,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of messages as follows","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":107,"keywordType":"Action","textWithKeyword":"When I select 'Unread' from the Read-Unread filter","stepMatchArguments":[{"group":{"start":10,"value":"Unread","children":[]}}]},{"pwStepLine":76,"gherkinStepLine":108,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of messages as follows","stepMatchArguments":[]}]},
  {"pwTestLine":79,"pickleLine":115,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":80,"gherkinStepLine":116,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":81,"gherkinStepLine":117,"keywordType":"Context","textWithKeyword":"And I am on the Business Messages page","stepMatchArguments":[{"group":{"start":12,"value":"Business Messages","children":[]}}]},{"pwStepLine":82,"gherkinStepLine":118,"keywordType":"Context","textWithKeyword":"And I have selected the contact 'Vilma Yundt'","stepMatchArguments":[{"group":{"start":29,"value":"Vilma Yundt","children":[]}}]},{"pwStepLine":83,"gherkinStepLine":119,"keywordType":"Action","textWithKeyword":"When I select the message with the subject 'THIS IS NOT CURRENTLY AVAILABLE'","stepMatchArguments":[{"group":{"start":39,"value":"THIS IS NOT CURRENTLY AVAILABLE","children":[]}}]},{"pwStepLine":84,"gherkinStepLine":120,"keywordType":"Outcome","textWithKeyword":"Then the Deleted field is 'true'","stepMatchArguments":[{"group":{"start":22,"value":"true","children":[]}}]},{"pwStepLine":85,"gherkinStepLine":121,"keywordType":"Action","textWithKeyword":"When I select the message with the subject 'Agnosco cohaero ancilla.  '","stepMatchArguments":[{"group":{"start":39,"value":"Agnosco cohaero ancilla.  ","children":[]}}]},{"pwStepLine":86,"gherkinStepLine":122,"keywordType":"Outcome","textWithKeyword":"Then the Deleted field is 'false'","stepMatchArguments":[{"group":{"start":22,"value":"false","children":[]}}]}]},
]; // bdd-data-end