// Generated from: test/features/business-land-details.feature
import { test } from "../../../test/features/steps/fixtures.js";

test.describe('Consolidated View Business Land Details page', () => {

  test('The Date selector updates the screen', { tag: ['@intermediate', '@incomplete'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have gone to the \'Land Details\' page', null, { page }); 
    await And('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await When('I select a new date', null, { businessLandDetailsPage }); 
    await Then('the page refreshes the data', null, { businessLandDetailsPage }); 
  });

  test('The Date selector cannot be blank', { tag: ['@intermediate', '@working'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have gone to the \'Land Details\' page', null, { page }); 
    await And('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await When('I delete all the text in the Date field', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('the date selector shows todays date', null, { businessLandDetailsPage }); 
  });

  test('The Date selector only accepts the correct date format - no non numeric characters', { tag: ['@intermediate'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have gone to the \'Land Details\' page', null, { page }); 
    await When('I enter \'aaa\' into the date picker', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see a warning message \'Date must be in dd/mm/yyy format. For example 25/12/2024\' under the \'Land Date\' table', null, { page }); 
  });

  test('The Date selector only accepts the correct date format - no incomplete dates', { tag: ['@intermediate'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have gone to the \'Land Details\' page', null, { page }); 
    await When('I enter \'01/01\' into the date picker', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see a warning message \'Date must be in dd/mm/yyy format. For example 25/12/2024\' under the \'Land Date\' table', null, { page }); 
  });

  test('The Date selector only accepts the correct date format - no incorrect dates', { tag: ['@intermediate'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have gone to the \'Land Details\' page', null, { page }); 
    await When('I enter \'32/32/32\' into the date picker', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see a warning message \'Date must be in dd/mm/yyy format. For example 25/12/2024\' under the \'Land Date\' table', null, { page }); 
  });

  test('The Date selector only accepts current or past dates', { tag: ['@intermediate'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have gone to the \'Land Details\' page', null, { page }); 
    await When('I enter \'31/12/2040\' into the date picker', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see a warning message \'Date must be todays date or in the past.\' under the \'Land Date\' table', null, { page }); 
  });

  test('The Date selected must be on or after 01/01/2015', { tag: ['@intermediate'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have gone to the \'Land Details\' page', null, { page }); 
    await When('I enter \'31/12/2014\' into the date picker', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see a warning message \'Date must on or after 01/01/2015\' under the \'Land Date\' table', null, { page }); 
  });

  test('Searching for a partially matching string in the Sheet column filters the Parcels table correctly.', { tag: ['@intermediate', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Land Details page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'SS66\' in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the correct list of parcels in the Parcels table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Sheet"},{"value":"SS6627"}]},{"cells":[{"value":"Parcel"},{"value":"5662"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Land Change?"},{"value":"No"}]}]}}, { businessLandDetailsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the correct list of parcels in the Parcels table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Sheet"},{"value":"SS6627, SS6828"}]},{"cells":[{"value":"Parcel"},{"value":"5662, 3818"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 1.027"}]},{"cells":[{"value":"Land Change?"},{"value":"No, No"}]}]}}, { businessLandDetailsPage }); 
  });

  test('Searching for a partially matching string in the Parcel column filters the Parcels table correctly.', { tag: ['@intermediate', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Land Details page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'818\' in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the correct list of parcels in the Parcels table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Sheet"},{"value":"SS6828"}]},{"cells":[{"value":"Parcel"},{"value":"3818"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Land Change?"},{"value":"No"}]}]}}, { businessLandDetailsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the correct list of parcels in the Parcels table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Sheet"},{"value":"SS6627, SS6828"}]},{"cells":[{"value":"Parcel"},{"value":"5662, 3818"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 1.027"}]},{"cells":[{"value":"Land Change?"},{"value":"No, No"}]}]}}, { businessLandDetailsPage }); 
  });

  test('An appropriate warning is shown when a business has no land entries.', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessLandDetailsPage, page }) => { 
    await Given('I have selected the business with SBI \'1000000000\'', null, { page }); 
    await When('I navigate to the Land Details page', null, { page }); 
    await Then('I see the following data in the Land Summary section', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Total Number of Parcels"},{"value":"0"}]},{"cells":[{"value":"Total Area (ha)"},{"value":"0"}]},{"cells":[{"value":"Total Parcels with Pending Customer Notified Land Changes"},{"value":"0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see the following data in the Land Summary table', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Code"},{"value":"110, 120, 130"}]},{"cells":[{"value":"Land Cover"},{"value":"Arable Land, Permanent grass land, Permanent crop land"}]},{"cells":[{"value":"Area (ha)"},{"value":"0, 0, 0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see a warning message \'We didn\'t find any data to show at this time\' under the \'Parcels\' table', null, { page }); 
  });

  test('Date formatting is handled correctly.', { tag: ['@advanced'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Land Details page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I select the first day of every month', null, { businessLandDetailsPage }); 
    await Then('no error is shown on screen', null, { businessLandDetailsPage }); 
  });

  test('Land details data is shown correctly for today\'s date', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1111111111\'', null, { page }); 
    await And('I am on the Land Details page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see the following data in the Land Summary section', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Total Number of Parcels"},{"value":"2"}]},{"cells":[{"value":"Total Area (ha)"},{"value":"2.0541"}]},{"cells":[{"value":"Total Parcels with Pending Customer Notified Land Changes"},{"value":"0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see the following data in the Land Summary table', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Code"},{"value":"110, 130, 140"}]},{"cells":[{"value":"Land Cover"},{"value":"Arable Land, Permanent Grassland, Permanent Crops"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 0, 0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see the correct list of parcels in the Parcels table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Sheet"},{"value":"SS6627, SS6828"}]},{"cells":[{"value":"Parcel"},{"value":"5662, 3818"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Land Change?"},{"value":"No, No"}]}]}}, { businessLandDetailsPage }); 
    await When('I click on the parcel \'SS6627 5662\'', null, { businessLandDetailsPage }); 
    await Then('I see a Parcel Summary section with a bold header \'SS6627 5662\'', null, { businessLandDetailsPage }); 
    await And('the Parcel Summary has field data as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Pending Customer Notified Land Change?"},{"value":"..."}]},{"cells":[{"value":"Effective Date From"},{"value":"25/07/2024"}]},{"cells":[{"value":"Effective Date To"},{"value":"25/07/2024"}]}]}}, { businessLandDetailsPage }); 
    await And('the Parcel Summary table has data as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Code"},{"value":"110, 131"}]},{"cells":[{"value":"Land Cover"},{"value":"Arable Land, Permanent Grassland"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 2.541"}]}]}}, { businessLandDetailsPage }); 
  });

  test('Land details data is shown correctly for the earliest valid date - 01/01/2015', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Land Details page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'01/01/2015\' into the date picker', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the following data in the Land Summary section', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Total Number of Parcels"},{"value":"2"}]},{"cells":[{"value":"Total Area (ha)"},{"value":"2.0541"}]},{"cells":[{"value":"Total Parcels with Pending Customer Notified Land Changes"},{"value":"0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see the following data in the Land Summary table', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Code"},{"value":"110, 130, 140"}]},{"cells":[{"value":"Land Cover"},{"value":"Arable Land, Permanent Grassland, Permanent Crops"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 0, 0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see the correct list of parcels in the Parcels table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Sheet"},{"value":"SS6627, SS6828"}]},{"cells":[{"value":"Parcel"},{"value":"5662, 3818"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Land Change?"},{"value":"No, No"}]}]}}, { businessLandDetailsPage }); 
    await When('I click on the parcel \'SS6627 5662\'', null, { businessLandDetailsPage }); 
    await Then('I see a Parcel Summary section with a bold header \'SS6627 5662\'', null, { businessLandDetailsPage }); 
    await And('the Parcel Summary has field data as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Pending Customer Notified Land Change?"},{"value":"..."}]},{"cells":[{"value":"Effective Date From"},{"value":"25/07/2024"}]},{"cells":[{"value":"Effective Date To"},{"value":"25/07/2024"}]}]}}, { businessLandDetailsPage }); 
    await And('the Parcel Summary table has data as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Code"},{"value":"110, 131"}]},{"cells":[{"value":"Land Cover"},{"value":"Arable Land, Permanent Grassland"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 2.541"}]}]}}, { businessLandDetailsPage }); 
  });

  test('Land details data is shown correctly for a valid date', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Land Details page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'15/06/2020\' into the date picker', null, { businessLandDetailsPage }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the following data in the Land Summary section', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Total Number of Parcels"},{"value":"2"}]},{"cells":[{"value":"Total Area (ha)"},{"value":"2.0541"}]},{"cells":[{"value":"Total Parcels with Pending Customer Notified Land Changes"},{"value":"0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see the following data in the Land Summary table', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Code"},{"value":"110, 130, 140"}]},{"cells":[{"value":"Land Cover"},{"value":"Arable Land, Permanent Grassland, Permanent Crops"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 0, 0"}]}]}}, { businessLandDetailsPage }); 
    await And('I see the correct list of parcels in the Parcels table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Sheet"},{"value":"SS6627, SS6828"}]},{"cells":[{"value":"Parcel"},{"value":"5662, 3818"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Land Change?"},{"value":"No, No"}]}]}}, { businessLandDetailsPage }); 
    await When('I click on the parcel \'SS6627 5662\'', null, { businessLandDetailsPage }); 
    await Then('I see a Parcel Summary section with a bold header \'SS6627 5662\'', null, { businessLandDetailsPage }); 
    await And('the Parcel Summary has field data as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027"}]},{"cells":[{"value":"Pending Customer Notified Land Change?"},{"value":"..."}]},{"cells":[{"value":"Effective Date From"},{"value":"25/07/2024"}]},{"cells":[{"value":"Effective Date To"},{"value":"25/07/2024"}]}]}}, { businessLandDetailsPage }); 
    await And('the Parcel Summary table has data as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Code"},{"value":"110, 131"}]},{"cells":[{"value":"Land Cover"},{"value":"Arable Land, Permanent Grassland"}]},{"cells":[{"value":"Area (ha)"},{"value":"1.027, 2.541"}]}]}}, { businessLandDetailsPage }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('test/features/business-land-details.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":6,"pickleLine":4,"tags":["@intermediate","@incomplete"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Land Details' page","stepMatchArguments":[{"group":{"start":20,"value":"Land Details","children":[]}}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I select a new date","stepMatchArguments":[]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then the page refreshes the data","stepMatchArguments":[]}]},
  {"pwTestLine":13,"pickleLine":11,"tags":["@intermediate","@working"],"steps":[{"pwStepLine":14,"gherkinStepLine":12,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Land Details' page","stepMatchArguments":[{"group":{"start":20,"value":"Land Details","children":[]}}]},{"pwStepLine":15,"gherkinStepLine":13,"keywordType":"Context","textWithKeyword":"And I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":16,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"When I delete all the text in the Date field","stepMatchArguments":[]},{"pwStepLine":17,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":18,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"Then the date selector shows todays date","stepMatchArguments":[]}]},
  {"pwTestLine":21,"pickleLine":19,"tags":["@intermediate"],"steps":[{"pwStepLine":22,"gherkinStepLine":20,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Land Details' page","stepMatchArguments":[{"group":{"start":20,"value":"Land Details","children":[]}}]},{"pwStepLine":23,"gherkinStepLine":21,"keywordType":"Action","textWithKeyword":"When I enter 'aaa' into the date picker","stepMatchArguments":[{"group":{"start":9,"value":"aaa","children":[]}}]},{"pwStepLine":24,"gherkinStepLine":22,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":25,"gherkinStepLine":23,"keywordType":"Outcome","textWithKeyword":"Then I see a warning message 'Date must be in dd/mm/yyy format. For example 25/12/2024' under the 'Land Date' table","stepMatchArguments":[{"group":{"start":25,"value":"Date must be in dd/mm/yyy format. For example 25/12/2024","children":[]}},{"group":{"start":94,"value":"Land Date","children":[]}}]}]},
  {"pwTestLine":28,"pickleLine":26,"tags":["@intermediate"],"steps":[{"pwStepLine":29,"gherkinStepLine":27,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Land Details' page","stepMatchArguments":[{"group":{"start":20,"value":"Land Details","children":[]}}]},{"pwStepLine":30,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"When I enter '01/01' into the date picker","stepMatchArguments":[{"group":{"start":9,"value":"01/01","children":[]}}]},{"pwStepLine":31,"gherkinStepLine":29,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":30,"keywordType":"Outcome","textWithKeyword":"Then I see a warning message 'Date must be in dd/mm/yyy format. For example 25/12/2024' under the 'Land Date' table","stepMatchArguments":[{"group":{"start":25,"value":"Date must be in dd/mm/yyy format. For example 25/12/2024","children":[]}},{"group":{"start":94,"value":"Land Date","children":[]}}]}]},
  {"pwTestLine":35,"pickleLine":33,"tags":["@intermediate"],"steps":[{"pwStepLine":36,"gherkinStepLine":34,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Land Details' page","stepMatchArguments":[{"group":{"start":20,"value":"Land Details","children":[]}}]},{"pwStepLine":37,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"When I enter '32/32/32' into the date picker","stepMatchArguments":[{"group":{"start":9,"value":"32/32/32","children":[]}}]},{"pwStepLine":38,"gherkinStepLine":36,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":39,"gherkinStepLine":37,"keywordType":"Outcome","textWithKeyword":"Then I see a warning message 'Date must be in dd/mm/yyy format. For example 25/12/2024' under the 'Land Date' table","stepMatchArguments":[{"group":{"start":25,"value":"Date must be in dd/mm/yyy format. For example 25/12/2024","children":[]}},{"group":{"start":94,"value":"Land Date","children":[]}}]}]},
  {"pwTestLine":42,"pickleLine":40,"tags":["@intermediate"],"steps":[{"pwStepLine":43,"gherkinStepLine":41,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Land Details' page","stepMatchArguments":[{"group":{"start":20,"value":"Land Details","children":[]}}]},{"pwStepLine":44,"gherkinStepLine":42,"keywordType":"Action","textWithKeyword":"When I enter '31/12/2040' into the date picker","stepMatchArguments":[{"group":{"start":9,"value":"31/12/2040","children":[]}}]},{"pwStepLine":45,"gherkinStepLine":43,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":46,"gherkinStepLine":44,"keywordType":"Outcome","textWithKeyword":"Then I see a warning message 'Date must be todays date or in the past.' under the 'Land Date' table","stepMatchArguments":[{"group":{"start":25,"value":"Date must be todays date or in the past.","children":[]}},{"group":{"start":78,"value":"Land Date","children":[]}}]}]},
  {"pwTestLine":49,"pickleLine":47,"tags":["@intermediate"],"steps":[{"pwStepLine":50,"gherkinStepLine":48,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Land Details' page","stepMatchArguments":[{"group":{"start":20,"value":"Land Details","children":[]}}]},{"pwStepLine":51,"gherkinStepLine":49,"keywordType":"Action","textWithKeyword":"When I enter '31/12/2014' into the date picker","stepMatchArguments":[{"group":{"start":9,"value":"31/12/2014","children":[]}}]},{"pwStepLine":52,"gherkinStepLine":50,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":51,"keywordType":"Outcome","textWithKeyword":"Then I see a warning message 'Date must on or after 01/01/2015' under the 'Land Date' table","stepMatchArguments":[{"group":{"start":25,"value":"Date must on or after 01/01/2015","children":[]}},{"group":{"start":70,"value":"Land Date","children":[]}}]}]},
  {"pwTestLine":56,"pickleLine":54,"tags":["@intermediate","@data-dependent"],"steps":[{"pwStepLine":57,"gherkinStepLine":55,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":58,"gherkinStepLine":56,"keywordType":"Context","textWithKeyword":"And I am on the Land Details page","stepMatchArguments":[{"group":{"start":12,"value":"Land Details","children":[]}}]},{"pwStepLine":59,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"When I enter 'SS66' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"SS66","children":[]}}]},{"pwStepLine":60,"gherkinStepLine":58,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":59,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of parcels in the Parcels table as follows","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":65,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":66,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":64,"gherkinStepLine":67,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of parcels in the Parcels table as follows","stepMatchArguments":[]}]},
  {"pwTestLine":67,"pickleLine":75,"tags":["@intermediate","@data-dependent"],"steps":[{"pwStepLine":68,"gherkinStepLine":76,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":69,"gherkinStepLine":77,"keywordType":"Context","textWithKeyword":"And I am on the Land Details page","stepMatchArguments":[{"group":{"start":12,"value":"Land Details","children":[]}}]},{"pwStepLine":70,"gherkinStepLine":78,"keywordType":"Action","textWithKeyword":"When I enter '818' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"818","children":[]}}]},{"pwStepLine":71,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":72,"gherkinStepLine":80,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of parcels in the Parcels table as follows","stepMatchArguments":[]},{"pwStepLine":73,"gherkinStepLine":86,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":74,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":75,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then I see the correct list of parcels in the Parcels table as follows","stepMatchArguments":[]}]},
  {"pwTestLine":78,"pickleLine":96,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":79,"gherkinStepLine":97,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1000000000'","stepMatchArguments":[{"group":{"start":39,"value":"1000000000","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":80,"gherkinStepLine":98,"keywordType":"Action","textWithKeyword":"When I navigate to the Land Details page","stepMatchArguments":[{"group":{"start":18,"value":"Land Details","children":[]}}]},{"pwStepLine":81,"gherkinStepLine":99,"keywordType":"Outcome","textWithKeyword":"Then I see the following data in the Land Summary section","stepMatchArguments":[]},{"pwStepLine":82,"gherkinStepLine":104,"keywordType":"Outcome","textWithKeyword":"And I see the following data in the Land Summary table","stepMatchArguments":[]},{"pwStepLine":83,"gherkinStepLine":109,"keywordType":"Outcome","textWithKeyword":"And I see a warning message 'We didn't find any data to show at this time' under the 'Parcels' table","stepMatchArguments":[{"group":{"start":25,"value":"We didn't find any data to show at this time","children":[]}},{"group":{"start":82,"value":"Parcels","children":[]}}]}]},
  {"pwTestLine":86,"pickleLine":112,"tags":["@advanced"],"steps":[{"pwStepLine":87,"gherkinStepLine":113,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":88,"gherkinStepLine":114,"keywordType":"Context","textWithKeyword":"And I am on the Land Details page","stepMatchArguments":[{"group":{"start":12,"value":"Land Details","children":[]}}]},{"pwStepLine":89,"gherkinStepLine":115,"keywordType":"Action","textWithKeyword":"When I select the first day of every month","stepMatchArguments":[]},{"pwStepLine":90,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"Then no error is shown on screen","stepMatchArguments":[]}]},
  {"pwTestLine":93,"pickleLine":119,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":94,"gherkinStepLine":120,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1111111111'","stepMatchArguments":[{"group":{"start":39,"value":"1111111111","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":95,"gherkinStepLine":121,"keywordType":"Context","textWithKeyword":"And I am on the Land Details page","stepMatchArguments":[{"group":{"start":12,"value":"Land Details","children":[]}}]},{"pwStepLine":96,"gherkinStepLine":122,"keywordType":"Outcome","textWithKeyword":"Then I see the following data in the Land Summary section","stepMatchArguments":[]},{"pwStepLine":97,"gherkinStepLine":127,"keywordType":"Outcome","textWithKeyword":"And I see the following data in the Land Summary table","stepMatchArguments":[]},{"pwStepLine":98,"gherkinStepLine":132,"keywordType":"Outcome","textWithKeyword":"And I see the correct list of parcels in the Parcels table as follows","stepMatchArguments":[]},{"pwStepLine":99,"gherkinStepLine":138,"keywordType":"Action","textWithKeyword":"When I click on the parcel 'SS6627 5662'","stepMatchArguments":[{"group":{"start":23,"value":"SS6627 5662","children":[]}}]},{"pwStepLine":100,"gherkinStepLine":139,"keywordType":"Outcome","textWithKeyword":"Then I see a Parcel Summary section with a bold header 'SS6627 5662'","stepMatchArguments":[{"group":{"start":51,"value":"SS6627 5662","children":[]}}]},{"pwStepLine":101,"gherkinStepLine":140,"keywordType":"Outcome","textWithKeyword":"And the Parcel Summary has field data as follows","stepMatchArguments":[]},{"pwStepLine":102,"gherkinStepLine":146,"keywordType":"Outcome","textWithKeyword":"And the Parcel Summary table has data as follows","stepMatchArguments":[]}]},
  {"pwTestLine":105,"pickleLine":153,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":106,"gherkinStepLine":154,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":107,"gherkinStepLine":155,"keywordType":"Context","textWithKeyword":"And I am on the Land Details page","stepMatchArguments":[{"group":{"start":12,"value":"Land Details","children":[]}}]},{"pwStepLine":108,"gherkinStepLine":156,"keywordType":"Action","textWithKeyword":"When I enter '01/01/2015' into the date picker","stepMatchArguments":[{"group":{"start":9,"value":"01/01/2015","children":[]}}]},{"pwStepLine":109,"gherkinStepLine":157,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":110,"gherkinStepLine":158,"keywordType":"Outcome","textWithKeyword":"Then I see the following data in the Land Summary section","stepMatchArguments":[]},{"pwStepLine":111,"gherkinStepLine":163,"keywordType":"Outcome","textWithKeyword":"And I see the following data in the Land Summary table","stepMatchArguments":[]},{"pwStepLine":112,"gherkinStepLine":168,"keywordType":"Outcome","textWithKeyword":"And I see the correct list of parcels in the Parcels table as follows","stepMatchArguments":[]},{"pwStepLine":113,"gherkinStepLine":174,"keywordType":"Action","textWithKeyword":"When I click on the parcel 'SS6627 5662'","stepMatchArguments":[{"group":{"start":23,"value":"SS6627 5662","children":[]}}]},{"pwStepLine":114,"gherkinStepLine":175,"keywordType":"Outcome","textWithKeyword":"Then I see a Parcel Summary section with a bold header 'SS6627 5662'","stepMatchArguments":[{"group":{"start":51,"value":"SS6627 5662","children":[]}}]},{"pwStepLine":115,"gherkinStepLine":176,"keywordType":"Outcome","textWithKeyword":"And the Parcel Summary has field data as follows","stepMatchArguments":[]},{"pwStepLine":116,"gherkinStepLine":182,"keywordType":"Outcome","textWithKeyword":"And the Parcel Summary table has data as follows","stepMatchArguments":[]}]},
  {"pwTestLine":119,"pickleLine":189,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":120,"gherkinStepLine":190,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":121,"gherkinStepLine":191,"keywordType":"Context","textWithKeyword":"And I am on the Land Details page","stepMatchArguments":[{"group":{"start":12,"value":"Land Details","children":[]}}]},{"pwStepLine":122,"gherkinStepLine":192,"keywordType":"Action","textWithKeyword":"When I enter '15/06/2020' into the date picker","stepMatchArguments":[{"group":{"start":9,"value":"15/06/2020","children":[]}}]},{"pwStepLine":123,"gherkinStepLine":193,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":124,"gherkinStepLine":194,"keywordType":"Outcome","textWithKeyword":"Then I see the following data in the Land Summary section","stepMatchArguments":[]},{"pwStepLine":125,"gherkinStepLine":199,"keywordType":"Outcome","textWithKeyword":"And I see the following data in the Land Summary table","stepMatchArguments":[]},{"pwStepLine":126,"gherkinStepLine":204,"keywordType":"Outcome","textWithKeyword":"And I see the correct list of parcels in the Parcels table as follows","stepMatchArguments":[]},{"pwStepLine":127,"gherkinStepLine":210,"keywordType":"Action","textWithKeyword":"When I click on the parcel 'SS6627 5662'","stepMatchArguments":[{"group":{"start":23,"value":"SS6627 5662","children":[]}}]},{"pwStepLine":128,"gherkinStepLine":211,"keywordType":"Outcome","textWithKeyword":"Then I see a Parcel Summary section with a bold header 'SS6627 5662'","stepMatchArguments":[{"group":{"start":51,"value":"SS6627 5662","children":[]}}]},{"pwStepLine":129,"gherkinStepLine":212,"keywordType":"Outcome","textWithKeyword":"And the Parcel Summary has field data as follows","stepMatchArguments":[]},{"pwStepLine":130,"gherkinStepLine":218,"keywordType":"Outcome","textWithKeyword":"And the Parcel Summary table has data as follows","stepMatchArguments":[]}]},
]; // bdd-data-end