// Generated from: test/features/business-linked-contacts.feature
import { test } from "../../../test/features/steps/fixtures.js";

test.describe('Consolidated View Business Linked Contacts page', () => {

  test('Clicking the View customer button navigates the user to the relevant Contacts page in CRM.', { tag: ['@intermediate', '@data-dependent', '@working'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have gone to the \'Business Linked Contacts\' page', null, { page }); 
    await Given('I have selected the business with SBI \'3333333333\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I select the contact with the CRN \'1111111901\' from the Contacts table', null, { businessLinkedContactsPage }); 
    await Then('the View Contact button is visible', null, { businessLinkedContactsPage }); 
  });

  test('On clicking on a customer, information is shown correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I select the contact with the CRN \'1103020285\' from the Contacts table', null, { businessLinkedContactsPage }); 
    await Then('the LinkedContacts page updates to show the following information', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Title"},{"value":"Merl Kemmer"}]},{"cells":[{"value":"CRN"},{"value":"1103020285"}]},{"cells":[{"value":"Full Name"},{"value":"Mr. Merl Elody Kemmer"}]},{"cells":[{"value":"Role"},{"value":"Business Partner"}]},{"cells":[{"value":"Permissions"},{"value":"BASIC_PAYMENT_SCHEME, BUSINESS_DETAILS, COUNTRYSIDE_STEWARDSHIP_AGREEMENTS, COUNTRYSIDE_STEWARDSHIP_APPLICATIONS, ENTITLEMENTS, ENVIRONMENTAL_LAND_MANAGEMENT_APPLICATIONS, LAND_DETAILS"}]},{"cells":[{"value":"Permissions Levels"},{"value":"SUBMIT, FULL_PERMISSION, SUBMIT, SUBMIT, AMEND, SUBMIT, AMEND"}]},{"cells":[{"value":"Permission Descriptions"},{"value":"View business summary, View claims, View land, features and covers, Create and edit a claim, Amend a previously submitted claim, Amend land, features and covers, Submit a claim"}]}]}}, { businessLinkedContactsPage }); 
  });

  test('On clicking on a Permission, the Permission Description table updates correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I select the Permission \'ENTITLEMENTS\' from the Permission table', null, { businessLinkedContactsPage }); 
    await Then('the LinkedContacts Permission Description table updates with the following descriptions \'View entitlements, Transfer entitlements, Apply for new entitlements\'', null, { businessLinkedContactsPage }); 
  });

  test('On clicking on a contact, information is shown correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I select the contact with the CRN \'1103969349\' from the Contacts table', null, { businessLinkedContactsPage }); 
    await Then('the LinkedContacts page updates to show the following information', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Title"},{"value":"Velma Deckow"}]},{"cells":[{"value":"CRN"},{"value":"1103969349"}]},{"cells":[{"value":"Full Name"},{"value":"Miss Velma Lavern Deckow"}]},{"cells":[{"value":"Role"},{"value":"Business Partner"}]},{"cells":[{"value":"Permissions"},{"value":"BASIC_PAYMENT_SCHEME, BUSINESS_DETAILS, COUNTRYSIDE_STEWARDSHIP_AGREEMENTS, COUNTRYSIDE_STEWARDSHIP_APPLICATIONS, ENTITLEMENTS, ENVIRONMENTAL_LAND_MANAGEMENT_APPLICATIONS, LAND_DETAILS"}]},{"cells":[{"value":"Permissions Levels"},{"value":"SUBMIT, FULL_PERMISSION, SUBMIT, SUBMIT, AMEND, SUBMIT, AMEND"}]},{"cells":[{"value":"Permission Descriptions"},{"value":"View business summary, View claims, View land, features and covers, Create and edit a claim, Amend a previously submitted claim, Amend land, features and covers, Submit a claim"}]}]}}, { businessLinkedContactsPage }); 
  });

  test('Searching for a partially matching string in the CRN column filters correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'3020\' in the search box', null, { page }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1103020285"}]},{"cells":[{"value":"First Name"},{"value":"Merl"}]},{"cells":[{"value":"Last Name"},{"value":"Kemmer"}]}]}}, { businessLinkedContactsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1103020285,1103969349"}]},{"cells":[{"value":"First Name"},{"value":"Merl,Velma"}]},{"cells":[{"value":"Last Name"},{"value":"Kemmer,Deckow"}]}]}}, { businessLinkedContactsPage }); 
  });

  test('Searching for a partially matching string in the First Name column filters correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'elm\' in the search box', null, { page }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1103969349"}]},{"cells":[{"value":"First Name"},{"value":"Velma"}]},{"cells":[{"value":"Last Name"},{"value":"Deckow"}]}]}}, { businessLinkedContactsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1103020285,1103969349"}]},{"cells":[{"value":"First Name"},{"value":"Merl,Velma"}]},{"cells":[{"value":"Last Name"},{"value":"Kemmer,Deckow"}]}]}}, { businessLinkedContactsPage }); 
  });

  test('Searching for a partially matching string in the Last Name column filters correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'emm\' in the search box', null, { page }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1103020285"}]},{"cells":[{"value":"First Name"},{"value":"Merl"}]},{"cells":[{"value":"Last Name"},{"value":"Kemmer"}]}]}}, { businessLinkedContactsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1103020285,1103969349"}]},{"cells":[{"value":"First Name"},{"value":"Merl,Velma"}]},{"cells":[{"value":"Last Name"},{"value":"Kemmer,Deckow"}]}]}}, { businessLinkedContactsPage }); 
  });

  test('Searching for a string that returns no results results in a warning message', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'1-2-3-a-b-c\' in the search box', null, { page }); 
    await Then('I see a warning \'There are no linked contacts for the search criteria entered\'', null, { businessLinkedContactsPage }); 
  });

  test('Clicking the \'View Authenticate Questions\' link displays a the correct information in the Contacts Authentication sub-screen', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsAuthenticationPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I select the contact with the CRN \'1103020285\' from the Contacts table', null, { businessLinkedContactsPage }); 
    await When('\'View Authenticate Questions\' link', null, { businessLinkedContactsPage }); 
    await Then('I see the Contacts Authentication sub-screen with the following information', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Title"},{"value":"0000000123"}]},{"cells":[{"value":"Full Name"},{"value":"Mr Merl Elody Kemmer"}]},{"cells":[{"value":"Role"},{"value":"Business Partner"}]},{"cells":[{"value":"Date of Birth"},{"value":"07/01/1963"}]},{"cells":[{"value":"Memorable Date"},{"value":"01/02/2003"}]},{"cells":[{"value":"Memorable Event"},{"value":"Bar Mitzvah"}]},{"cells":[{"value":"Memorable Place"},{"value":"Vegas"}]},{"cells":[{"value":"Updated Date"},{"value":"01/01/2025"}]}]}}, { businessLinkedContactsAuthenticationPage }); 
  });

  test('The correct Linked Contacts are shown for a business', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1103020285,1103969349"}]},{"cells":[{"value":"First Name"},{"value":"Merl,Velma"}]},{"cells":[{"value":"Last Name"},{"value":"Kemmer,Deckow"}]}]}}, { businessLinkedContactsPage }); 
  });

  test('A contact with no contacts is shown with a warning', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1000000000\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see the \'Contacts\' table is empty', null, { page }); 
    await And('I see a warning \'There are no linked contacts for this business with SBI 1000000000\'', null, { businessLinkedContactsPage }); 
  });

  test('When a contact\'s permission is NOT level "NO_ACCESS", the Permission Description list is correct.', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'107591843\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I select the contact with the CRN \'1103969349\' from the Contacts table', null, { businessLinkedContactsPage }); 
    await And('I select the Permission \'BASIC_PAYMENT_SCHEME\' from the Permission table', null, { businessLinkedContactsPage }); 
    await Then('I see the LinkedContacts Permission Description table with \'View business summary, View claims, View land, features and covers, Create and edit a claim, Amend a previously submitted claim, Amend land, features and covers, Submit a claim\'', null, { businessLinkedContactsPage }); 
  });

  test('When a contact has no first name, data is displayed correctly on the Linked Contacts screen', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'3333333333\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I select the contact with the CRN \'1111111901\' from the Contacts table', null, { businessLinkedContactsPage }); 
    await Then('I see the the correct list of contacts as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"CRN"},{"value":"1111111901"}]},{"cells":[{"value":"First Name"},{"value":""}]},{"cells":[{"value":"Last Name"},{"value":"Grey"}]}]}}, { businessLinkedContactsPage }); 
    await And('the LinkedContacts page updates to show the following information', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Title"},{"value":"Lady Grey"}]},{"cells":[{"value":"CRN"},{"value":"1111111901"}]},{"cells":[{"value":"Full Name"},{"value":"Lady Grey"}]},{"cells":[{"value":"Role"},{"value":"Business Partner"}]},{"cells":[{"value":"Permissions"},{"value":"BASIC_PAYMENT_SCHEME, BUSINESS_DETAILS, COUNTRYSIDE_STEWARDSHIP_AGREEMENTS, COUNTRYSIDE_STEWARDSHIP_APPLICATIONS, ENTITLEMENTS, ENVIRONMENTAL_LAND_MANAGEMENT_APPLICATIONS, LAND_DETAILS"}]},{"cells":[{"value":"Permissions Levels"},{"value":"SUBMIT, FULL_PERMISSION, SUBMIT, SUBMIT, AMEND, SUBMIT, AMEND"}]},{"cells":[{"value":"Permission Descriptions"},{"value":"View business summary, View claims, View land, features and covers, Create and edit a claim, Amend a previously submitted claim, Amend land, features and covers, Submit a claim"}]}]}}, { businessLinkedContactsPage }); 
  });

  test('When a contact\'s permission is level "NO_ACCESS", the Permission Description list shows the correct warning message "We didn\'t find any data to show at this time".', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'3333333333\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I select the contact with the CRN \'1111111901\' from the Contacts table', null, { businessLinkedContactsPage }); 
    await And('I select the Permission \'LAND_DETAILS\' from the Permission table', null, { businessLinkedContactsPage }); 
    await Then('I see the \'Permission Description\' table is empty', null, { page }); 
    await And('I see a warning message \'We didn\'t find any data to show at this time\' under the \'Permission Description\' table', null, { page }); 
  });

  test('If the user does not have the correct permissions to see data they have requested, the user is shown an error message (401)', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I am logged in as user \'DEF\'', null, { page }); 
    await And('I have selected the business with SBI \'3000000401\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see a warning \'You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.\'', null, { businessLinkedContactsPage }); 
  });

  test('If the user does not have the correct permissions to see data they have requested, the user is shown an error message (403)', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I am logged in as user \'DEF\'', null, { page }); 
    await And('I have selected the business with SBI \'3000000403\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see a warning \'You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.\'', null, { businessLinkedContactsPage }); 
  });

  test('If CV encounters an error while loading the page, the user is shown an error message', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'3000000500\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see a warning \'An error has occurred. Error code 500 was returned from the DAL.\'', null, { businessLinkedContactsPage }); 
  });

  test('If the SBI cannot be found, the user is shown an error message', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'1010101010\'', null, { page }); 
    await And('I am on the Business Linked Contacts page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see a warning \'Business with SBI 1010101010 was not found\'', null, { businessLinkedContactsPage }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('test/features/business-linked-contacts.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":6,"pickleLine":5,"tags":["@intermediate","@data-dependent","@working"],"steps":[{"pwStepLine":7,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Business Linked Contacts' page","stepMatchArguments":[{"group":{"start":20,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":8,"gherkinStepLine":7,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '3333333333'","stepMatchArguments":[{"group":{"start":39,"value":"3333333333","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":9,"gherkinStepLine":8,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":10,"gherkinStepLine":9,"keywordType":"Context","textWithKeyword":"And I select the contact with the CRN '1111111901' from the Contacts table","stepMatchArguments":[{"group":{"start":35,"value":"1111111901","children":[]}}]},{"pwStepLine":11,"gherkinStepLine":10,"keywordType":"Outcome","textWithKeyword":"Then the View Contact button is visible","stepMatchArguments":[]}]},
  {"pwTestLine":14,"pickleLine":15,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":15,"gherkinStepLine":16,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":16,"gherkinStepLine":17,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":17,"gherkinStepLine":18,"keywordType":"Action","textWithKeyword":"When I select the contact with the CRN '1103020285' from the Contacts table","stepMatchArguments":[{"group":{"start":35,"value":"1103020285","children":[]}}]},{"pwStepLine":18,"gherkinStepLine":19,"keywordType":"Outcome","textWithKeyword":"Then the LinkedContacts page updates to show the following information","stepMatchArguments":[]}]},
  {"pwTestLine":21,"pickleLine":30,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":22,"gherkinStepLine":31,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":23,"gherkinStepLine":32,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":24,"gherkinStepLine":33,"keywordType":"Action","textWithKeyword":"When I select the Permission 'ENTITLEMENTS' from the Permission table","stepMatchArguments":[{"group":{"start":25,"value":"ENTITLEMENTS","children":[]}}]},{"pwStepLine":25,"gherkinStepLine":34,"keywordType":"Outcome","textWithKeyword":"Then the LinkedContacts Permission Description table updates with the following descriptions 'View entitlements, Transfer entitlements, Apply for new entitlements'","stepMatchArguments":[{"group":{"start":89,"value":"View entitlements, Transfer entitlements, Apply for new entitlements","children":[]}}]}]},
  {"pwTestLine":28,"pickleLine":37,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":29,"gherkinStepLine":38,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":30,"gherkinStepLine":39,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":31,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"When I select the contact with the CRN '1103969349' from the Contacts table","stepMatchArguments":[{"group":{"start":35,"value":"1103969349","children":[]}}]},{"pwStepLine":32,"gherkinStepLine":41,"keywordType":"Outcome","textWithKeyword":"Then the LinkedContacts page updates to show the following information","stepMatchArguments":[]}]},
  {"pwTestLine":35,"pickleLine":52,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":36,"gherkinStepLine":53,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":37,"gherkinStepLine":54,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":38,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"When I enter '3020' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"3020","children":[]}}]},{"pwStepLine":39,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]},{"pwStepLine":40,"gherkinStepLine":61,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":62,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":63,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]}]},
  {"pwTestLine":45,"pickleLine":70,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":46,"gherkinStepLine":71,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":47,"gherkinStepLine":72,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":48,"gherkinStepLine":73,"keywordType":"Action","textWithKeyword":"When I enter 'elm' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"elm","children":[]}}]},{"pwStepLine":49,"gherkinStepLine":74,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]},{"pwStepLine":50,"gherkinStepLine":79,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":80,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":81,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]}]},
  {"pwTestLine":55,"pickleLine":88,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":56,"gherkinStepLine":89,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":57,"gherkinStepLine":90,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":58,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"When I enter 'emm' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"emm","children":[]}}]},{"pwStepLine":59,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]},{"pwStepLine":60,"gherkinStepLine":97,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":98,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":99,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]}]},
  {"pwTestLine":65,"pickleLine":106,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":66,"gherkinStepLine":107,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":67,"gherkinStepLine":108,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":68,"gherkinStepLine":109,"keywordType":"Action","textWithKeyword":"When I enter '1-2-3-a-b-c' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"1-2-3-a-b-c","children":[]}}]},{"pwStepLine":69,"gherkinStepLine":110,"keywordType":"Outcome","textWithKeyword":"Then I see a warning 'There are no linked contacts for the search criteria entered'","stepMatchArguments":[{"group":{"start":16,"value":"'There are no linked contacts for the search criteria entered'","children":[{"children":[{"children":[]}]},{"start":17,"value":"There are no linked contacts for the search criteria entered","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":72,"pickleLine":113,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":73,"gherkinStepLine":114,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":74,"gherkinStepLine":115,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":75,"gherkinStepLine":116,"keywordType":"Context","textWithKeyword":"And I select the contact with the CRN '1103020285' from the Contacts table","stepMatchArguments":[{"group":{"start":35,"value":"1103020285","children":[]}}]},{"pwStepLine":76,"gherkinStepLine":117,"keywordType":"Action","textWithKeyword":"When 'View Authenticate Questions' link","stepMatchArguments":[]},{"pwStepLine":77,"gherkinStepLine":118,"keywordType":"Outcome","textWithKeyword":"Then I see the Contacts Authentication sub-screen with the following information","stepMatchArguments":[]}]},
  {"pwTestLine":80,"pickleLine":130,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":81,"gherkinStepLine":131,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":82,"gherkinStepLine":132,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":83,"gherkinStepLine":133,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]}]},
  {"pwTestLine":86,"pickleLine":140,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":87,"gherkinStepLine":141,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1000000000'","stepMatchArguments":[{"group":{"start":39,"value":"1000000000","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":88,"gherkinStepLine":142,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":89,"gherkinStepLine":143,"keywordType":"Outcome","textWithKeyword":"Then I see the 'Contacts' table is empty","stepMatchArguments":[{"group":{"start":11,"value":"Contacts","children":[]}}]},{"pwStepLine":90,"gherkinStepLine":144,"keywordType":"Outcome","textWithKeyword":"And I see a warning 'There are no linked contacts for this business with SBI 1000000000'","stepMatchArguments":[{"group":{"start":16,"value":"'There are no linked contacts for this business with SBI 1000000000'","children":[{"children":[{"children":[]}]},{"start":17,"value":"There are no linked contacts for this business with SBI 1000000000","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":93,"pickleLine":147,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":94,"gherkinStepLine":148,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '107591843'","stepMatchArguments":[{"group":{"start":39,"value":"107591843","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":95,"gherkinStepLine":149,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":96,"gherkinStepLine":150,"keywordType":"Context","textWithKeyword":"And I select the contact with the CRN '1103969349' from the Contacts table","stepMatchArguments":[{"group":{"start":35,"value":"1103969349","children":[]}}]},{"pwStepLine":97,"gherkinStepLine":151,"keywordType":"Context","textWithKeyword":"And I select the Permission 'BASIC_PAYMENT_SCHEME' from the Permission table","stepMatchArguments":[{"group":{"start":25,"value":"BASIC_PAYMENT_SCHEME","children":[]}}]},{"pwStepLine":98,"gherkinStepLine":152,"keywordType":"Outcome","textWithKeyword":"Then I see the LinkedContacts Permission Description table with 'View business summary, View claims, View land, features and covers, Create and edit a claim, Amend a previously submitted claim, Amend land, features and covers, Submit a claim'","stepMatchArguments":[{"group":{"start":59,"value":"'View business summary, View claims, View land, features and covers, Create and edit a claim, Amend a previously submitted claim, Amend land, features and covers, Submit a claim'","children":[{"children":[{"children":[]}]},{"start":60,"value":"View business summary, View claims, View land, features and covers, Create and edit a claim, Amend a previously submitted claim, Amend land, features and covers, Submit a claim","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":101,"pickleLine":155,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":102,"gherkinStepLine":156,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '3333333333'","stepMatchArguments":[{"group":{"start":39,"value":"3333333333","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":103,"gherkinStepLine":157,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":104,"gherkinStepLine":158,"keywordType":"Context","textWithKeyword":"And I select the contact with the CRN '1111111901' from the Contacts table","stepMatchArguments":[{"group":{"start":35,"value":"1111111901","children":[]}}]},{"pwStepLine":105,"gherkinStepLine":159,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of contacts as follows","stepMatchArguments":[]},{"pwStepLine":106,"gherkinStepLine":164,"keywordType":"Outcome","textWithKeyword":"And the LinkedContacts page updates to show the following information","stepMatchArguments":[]}]},
  {"pwTestLine":109,"pickleLine":175,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":110,"gherkinStepLine":176,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '3333333333'","stepMatchArguments":[{"group":{"start":39,"value":"3333333333","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":111,"gherkinStepLine":177,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":112,"gherkinStepLine":178,"keywordType":"Context","textWithKeyword":"And I select the contact with the CRN '1111111901' from the Contacts table","stepMatchArguments":[{"group":{"start":35,"value":"1111111901","children":[]}}]},{"pwStepLine":113,"gherkinStepLine":179,"keywordType":"Context","textWithKeyword":"And I select the Permission 'LAND_DETAILS' from the Permission table","stepMatchArguments":[{"group":{"start":25,"value":"LAND_DETAILS","children":[]}}]},{"pwStepLine":114,"gherkinStepLine":180,"keywordType":"Outcome","textWithKeyword":"Then I see the 'Permission Description' table is empty","stepMatchArguments":[{"group":{"start":11,"value":"Permission Description","children":[]}}]},{"pwStepLine":115,"gherkinStepLine":181,"keywordType":"Outcome","textWithKeyword":"And I see a warning message 'We didn't find any data to show at this time' under the 'Permission Description' table","stepMatchArguments":[{"group":{"start":25,"value":"We didn't find any data to show at this time","children":[]}},{"group":{"start":82,"value":"Permission Description","children":[]}}]}]},
  {"pwTestLine":118,"pickleLine":184,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":119,"gherkinStepLine":185,"keywordType":"Context","textWithKeyword":"Given I am logged in as user 'DEF'","stepMatchArguments":[{"group":{"start":24,"value":"DEF","children":[]}}]},{"pwStepLine":120,"gherkinStepLine":186,"keywordType":"Context","textWithKeyword":"And I have selected the business with SBI '3000000401'","stepMatchArguments":[{"group":{"start":39,"value":"3000000401","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":121,"gherkinStepLine":187,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":122,"gherkinStepLine":188,"keywordType":"Outcome","textWithKeyword":"Then I see a warning 'You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.'","stepMatchArguments":[{"group":{"start":16,"value":"'You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.'","children":[{"children":[{"children":[]}]},{"start":17,"value":"You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":125,"pickleLine":191,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":126,"gherkinStepLine":192,"keywordType":"Context","textWithKeyword":"Given I am logged in as user 'DEF'","stepMatchArguments":[{"group":{"start":24,"value":"DEF","children":[]}}]},{"pwStepLine":127,"gherkinStepLine":193,"keywordType":"Context","textWithKeyword":"And I have selected the business with SBI '3000000403'","stepMatchArguments":[{"group":{"start":39,"value":"3000000403","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":128,"gherkinStepLine":194,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":129,"gherkinStepLine":195,"keywordType":"Outcome","textWithKeyword":"Then I see a warning 'You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.'","stepMatchArguments":[{"group":{"start":16,"value":"'You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.'","children":[{"children":[{"children":[]}]},{"start":17,"value":"You do not have permissions to view this data. Make sure you have an active Rural Payments Portal account with email address xxx@xxx.xxx. See Consolidated View guidance for for more information.","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":132,"pickleLine":199,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":133,"gherkinStepLine":200,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '3000000500'","stepMatchArguments":[{"group":{"start":39,"value":"3000000500","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":134,"gherkinStepLine":201,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":135,"gherkinStepLine":202,"keywordType":"Outcome","textWithKeyword":"Then I see a warning 'An error has occurred. Error code 500 was returned from the DAL.'","stepMatchArguments":[{"group":{"start":16,"value":"'An error has occurred. Error code 500 was returned from the DAL.'","children":[{"children":[{"children":[]}]},{"start":17,"value":"An error has occurred. Error code 500 was returned from the DAL.","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
  {"pwTestLine":138,"pickleLine":205,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":139,"gherkinStepLine":206,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1010101010'","stepMatchArguments":[{"group":{"start":39,"value":"1010101010","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":140,"gherkinStepLine":207,"keywordType":"Context","textWithKeyword":"And I am on the Business Linked Contacts page","stepMatchArguments":[{"group":{"start":12,"value":"Business Linked Contacts","children":[]}}]},{"pwStepLine":141,"gherkinStepLine":208,"keywordType":"Outcome","textWithKeyword":"Then I see a warning 'Business with SBI 1010101010 was not found'","stepMatchArguments":[{"group":{"start":16,"value":"'Business with SBI 1010101010 was not found'","children":[{"children":[{"children":[]}]},{"start":17,"value":"Business with SBI 1010101010 was not found","children":[{"children":[]}]}]},"parameterTypeName":"string"}]}]},
]; // bdd-data-end