// Generated from: test/features/business-applications.feature
import { test } from "../../../test/features/steps/fixtures.js";

test.describe('Consolidated View Applications page', () => {

  test('Searching for a partially matching string in the Application ID column filters correctly', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'658\' in the search box', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203658"}]},{"cells":[{"value":"Year"},{"value":"2025"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS"}]}]}}, { businessApplicationsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Year"},{"value":"2025,2024,2023"}]},{"cells":[{"value":"Application ID"},{"value":"2203658, 2203641, 2200679"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim, Domestic Capital Claim, CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS, IN PROGRESS, SUBMITTED"}]}]}}, { businessApplicationsPage }); 
  });

  test('Searching for a partially matching string in the Year column filters correctly', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'2024\' in the search box', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203641"}]},{"cells":[{"value":"Year"},{"value":"2024"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS"}]}]}}, { businessApplicationsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203658, 2203641, 2200679"}]},{"cells":[{"value":"Year"},{"value":"2025,2024,2023"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim, Domestic Capital Claim, CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS, IN PROGRESS, SUBMITTED"}]}]}}, { businessApplicationsPage }); 
  });

  test('Searching for a partially matching string in the Application Name column filters correctly', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'Domestic\' in the search box', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203658,2203641"}]},{"cells":[{"value":"Year"},{"value":"2025,2024"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim, Domestic Capital Claim"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS, IN PROGRESS"}]}]}}, { businessApplicationsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203658, 2203641, 2200679"}]},{"cells":[{"value":"Year"},{"value":"2025,2024,2023"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim, Domestic Capital Claim, CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS, IN PROGRESS, SUBMITTED"}]}]}}, { businessApplicationsPage }); 
  });

  test('Searching for a partially matching string in the Status column filters correctly', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'SUBM\' in the search box', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2200679"}]},{"cells":[{"value":"Year"},{"value":"2023"}]},{"cells":[{"value":"Application Name"},{"value":"CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"SUBMITTED"}]}]}}, { businessApplicationsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203658, 2203641, 2200679"}]},{"cells":[{"value":"Year"},{"value":"2025,2024,2023"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim, Domestic Capital Claim, CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS, IN PROGRESS, SUBMITTED"}]}]}}, { businessApplicationsPage }); 
  });

  test('Searching for a partially matching string in the Scheme column filters correctly', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'PILLAR II\' in the search box', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2200679"}]},{"cells":[{"value":"Year"},{"value":"2023"}]},{"cells":[{"value":"Application Name"},{"value":"CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"SUBMITTED"}]}]}}, { businessApplicationsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203658, 2203641, 2200679"}]},{"cells":[{"value":"Year"},{"value":"2025,2024,2023"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim, Domestic Capital Claim, CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS, IN PROGRESS, SUBMITTED"}]}]}}, { businessApplicationsPage }); 
  });

  test('Searching for a partially matching string in the Agreement References column filters correctly', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'0000000001\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'65676\' in the search box', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203641"}]},{"cells":[{"value":"Year"},{"value":"2024"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS"}]}]}}, { businessApplicationsPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of Applications as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Application ID"},{"value":"2203658, 2203641, 2200679"}]},{"cells":[{"value":"Year"},{"value":"2025,2024,2023"}]},{"cells":[{"value":"Application Name"},{"value":"Domestic Capital Claim, Domestic Capital Claim, CO Rev Payments"}]},{"cells":[{"value":"Status"},{"value":"IN PROGRESS, IN PROGRESS, SUBMITTED"}]}]}}, { businessApplicationsPage }); 
  });

  test('For a business with no Applications, a warning message is shown indicating that there are no Applications', { tag: ['@advanced', '@data-dependent', '@working'] }, async ({ Given, Then, And, businessApplicationsPage, page }) => { 
    await Given('I have gone to the \'Applications\' page', null, { page }); 
    await Given('I have selected the business with SBI \'1000000000\'', null, { page }); 
    await Then('I see the \'Applications\' table is empty', null, { page }); 
    await And('the Applications details pane is empty', null, { businessApplicationsPage }); 
    await And('I see a warning message \'No results found\' under the \'Application Details\' table', null, { page }); 
  });

  test('The Applications data is correct', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'106238988\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected an application with the ID \'9098148058\'', null, { businessApplicationsPage }); 
    await Then('I see the correct data in the Application Details pane as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Title"},{"value":"SOLITO ABSQUE DECET DEMONSTRO REPREHENDERIT VIA SOLLERS UBI"}]},{"cells":[{"value":"Application ID"},{"value":"9098148058"}]},{"cells":[{"value":"Scheme"},{"value":"BIS DERIPIO SUFFICIO SUPPELLEX VILICUS"}]},{"cells":[{"value":"Year"},{"value":"2022"}]},{"cells":[{"value":"Status"},{"value":"DELETED"}]},{"cells":[{"value":"Status (Portal)"},{"value":"..."}]},{"cells":[{"value":"Submitted Date"},{"value":"31/12/2022 03:33:24"}]},{"cells":[{"value":"Agreement References"},{"value":"9190356161"}]},{"cells":[{"value":"Last Movement"},{"value":"CREATE DRAFT APPLICATION"}]},{"cells":[{"value":"Last Movement Date/Time"},{"value":"31/12/2022 07:15:25"}]}]}}, { businessApplicationsPage }); 
    await And('I see the correct data in the Movements History table as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Date/Time"},{"value":"31/12/2022 07:15:25, 31/12/2022 21:03:16, 31/12/2022 02:09:35"}]},{"cells":[{"value":"Movement"},{"value":"CREATE DRAFT APPLICATION,DELETE, CREATION"}]},{"cells":[{"value":"Check"},{"value":"PASSED, PASSED, NOT PASSED"}]}]}}, { businessApplicationsPage }); 
  });

  test('The “Movements History” table is ordered by date/time', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the business with SBI \'106238988\'', null, { page }); 
    await And('I am on the Applications page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected an application with the ID \'1890586021\'', null, { businessApplicationsPage }); 
    await And('I see the correct data in the Movements History table ordered by date/time as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Date/Time"},{"value":"31/12/2022 21:30:55, 31/12/2022 13:21:28, 31/12/2022 11:41:13, 31/12/2022 08:15:03, 31/12/2022 05:50:06"}]},{"cells":[{"value":"Movement"},{"value":"UPDATE, UPDATE, CREATION, UPDATE, UPDATE"}]},{"cells":[{"value":"Check"},{"value":"PASSED, PASSED, PASSED, PASSED, PASSED"}]}]}}, { businessApplicationsPage }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('test/features/business-applications.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":6,"pickleLine":4,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Action","textWithKeyword":"When I enter '658' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"658","children":[]}}]},{"pwStepLine":10,"gherkinStepLine":8,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]},{"pwStepLine":11,"gherkinStepLine":14,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":12,"gherkinStepLine":15,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":13,"gherkinStepLine":16,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]}]},
  {"pwTestLine":16,"pickleLine":24,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":17,"gherkinStepLine":25,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":18,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":19,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When I enter '2024' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"2024","children":[]}}]},{"pwStepLine":20,"gherkinStepLine":28,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]},{"pwStepLine":21,"gherkinStepLine":34,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":22,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":23,"gherkinStepLine":36,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]}]},
  {"pwTestLine":26,"pickleLine":44,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":27,"gherkinStepLine":45,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":28,"gherkinStepLine":46,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":29,"gherkinStepLine":47,"keywordType":"Action","textWithKeyword":"When I enter 'Domestic' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"Domestic","children":[]}}]},{"pwStepLine":30,"gherkinStepLine":48,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]},{"pwStepLine":31,"gherkinStepLine":54,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":55,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":56,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]}]},
  {"pwTestLine":36,"pickleLine":64,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":37,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":38,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":39,"gherkinStepLine":67,"keywordType":"Action","textWithKeyword":"When I enter 'SUBM' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"SUBM","children":[]}}]},{"pwStepLine":40,"gherkinStepLine":68,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]},{"pwStepLine":41,"gherkinStepLine":74,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":75,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":76,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]}]},
  {"pwTestLine":46,"pickleLine":84,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":47,"gherkinStepLine":85,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":48,"gherkinStepLine":86,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":49,"gherkinStepLine":87,"keywordType":"Action","textWithKeyword":"When I enter 'PILLAR II' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"PILLAR II","children":[]}}]},{"pwStepLine":50,"gherkinStepLine":88,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]},{"pwStepLine":51,"gherkinStepLine":94,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":95,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":53,"gherkinStepLine":96,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]}]},
  {"pwTestLine":56,"pickleLine":104,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":57,"gherkinStepLine":105,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '0000000001'","stepMatchArguments":[{"group":{"start":39,"value":"0000000001","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":58,"gherkinStepLine":106,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":59,"gherkinStepLine":107,"keywordType":"Action","textWithKeyword":"When I enter '65676' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"65676","children":[]}}]},{"pwStepLine":60,"gherkinStepLine":108,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]},{"pwStepLine":61,"gherkinStepLine":114,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":62,"gherkinStepLine":115,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":63,"gherkinStepLine":116,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of Applications as follows","stepMatchArguments":[]}]},
  {"pwTestLine":66,"pickleLine":124,"tags":["@advanced","@data-dependent","@working"],"steps":[{"pwStepLine":67,"gherkinStepLine":125,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Applications' page","stepMatchArguments":[{"group":{"start":20,"value":"Applications","children":[]}}]},{"pwStepLine":68,"gherkinStepLine":126,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '1000000000'","stepMatchArguments":[{"group":{"start":39,"value":"1000000000","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":69,"gherkinStepLine":127,"keywordType":"Outcome","textWithKeyword":"Then I see the 'Applications' table is empty","stepMatchArguments":[{"group":{"start":11,"value":"Applications","children":[]}}]},{"pwStepLine":70,"gherkinStepLine":128,"keywordType":"Outcome","textWithKeyword":"And the Applications details pane is empty","stepMatchArguments":[]},{"pwStepLine":71,"gherkinStepLine":129,"keywordType":"Outcome","textWithKeyword":"And I see a warning message 'No results found' under the 'Application Details' table","stepMatchArguments":[{"group":{"start":25,"value":"No results found","children":[]}},{"group":{"start":54,"value":"Application Details","children":[]}}]}]},
  {"pwTestLine":74,"pickleLine":132,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":75,"gherkinStepLine":133,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '106238988'","stepMatchArguments":[{"group":{"start":39,"value":"106238988","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":76,"gherkinStepLine":134,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":77,"gherkinStepLine":135,"keywordType":"Context","textWithKeyword":"And I have selected an application with the ID '9098148058'","stepMatchArguments":[{"group":{"start":44,"value":"9098148058","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":78,"gherkinStepLine":136,"keywordType":"Outcome","textWithKeyword":"Then I see the correct data in the Application Details pane as follows","stepMatchArguments":[]},{"pwStepLine":79,"gherkinStepLine":148,"keywordType":"Outcome","textWithKeyword":"And I see the correct data in the Movements History table as follows","stepMatchArguments":[]}]},
  {"pwTestLine":82,"pickleLine":155,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":83,"gherkinStepLine":156,"keywordType":"Context","textWithKeyword":"Given I have selected the business with SBI '106238988'","stepMatchArguments":[{"group":{"start":39,"value":"106238988","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":84,"gherkinStepLine":157,"keywordType":"Context","textWithKeyword":"And I am on the Applications page","stepMatchArguments":[{"group":{"start":12,"value":"Applications","children":[]}}]},{"pwStepLine":85,"gherkinStepLine":158,"keywordType":"Context","textWithKeyword":"And I have selected an application with the ID '1890586021'","stepMatchArguments":[{"group":{"start":44,"value":"1890586021","children":[]},"parameterTypeName":"int"}]},{"pwStepLine":86,"gherkinStepLine":159,"keywordType":"Context","textWithKeyword":"And I see the correct data in the Movements History table ordered by date/time as follows","stepMatchArguments":[]}]},
]; // bdd-data-end