// Generated from: test/features/contacts-linked-businesses.feature
import { test } from "../../../test/features/steps/fixtures.js";

test.describe('Consolidated View Contacts Linked Businesses page', () => {

  test('A contact with no businesses is shown without error', { tag: ['@advanced', '@data-dependent', '@working'] }, async ({ Given, Then, And, page }) => { 
    await Given('I have gone to the \'Contacts Linked Businesses\' page', null, { page }); 
    await And('I have selected the contact with CRN \'9000000000\'', null, { page }); 
    await Then('I see the \'Businesses\' table is empty', null, { page }); 
  });

  test('On clicking on a business, information is shown correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'1103020285\'', null, { page }); 
    await And('I am on the Contacts Linked Businesses page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I select the business \'Bailey, Dickens and Mraz\' from the Businesses table', null, { contactsLinkedBusinessesPage }); 
    await Then('the LinkedBusinesses page updates to show the following information', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"Title"},{"value":"Bailey, Dickens and Mraz"}]},{"cells":[{"value":"SBI"},{"value":"1103020285"}]},{"cells":[{"value":"Role"},{"value":"Business Partner"}]},{"cells":[{"value":"Permissions"},{"value":"BASIC_PAYMENT_SCHEME, BUSINESS_DETAILS, COUNTRYSIDE_STEWARDSHIP_AGREEMENTS, COUNTRYSIDE_STEWARDSHIP_APPLICATIONS, ENTITLEMENTS, ENVIRONMENTAL_LAND_MANAGEMENT_APPLICATIONS, LAND_DETAILS"}]},{"cells":[{"value":"Permissions Levels"},{"value":"SUBMIT, FULL_PERMISSION, SUBMIT, SUBMIT, AMEND, SUBMIT, AMEND"}]},{"cells":[{"value":"Permission Descriptions"},{"value":"View business summary, View claims, \"View land, features and covers\", Create and edit a claim, Amend a previously submitted claim, \"Amend land, features and covers\", Submit a claim, Withdraw a claim, \"Receive warnings and notifications\""}]}]}}, { contactsLinkedBusinessesPage }); 
  });

  test('On clicking on a Permission, the Permission Description table updates correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'1103020285\'', null, { page }); 
    await And('I am on the Contacts Linked Businesses page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I select the business \'Goldner, Schmeler and Kutch\' from the Businesses table', null, { contactsLinkedBusinessesPage }); 
    await And('I select the Permission \'ENTITLEMENTS\' from the Permissions table', null, { contactsLinkedBusinessesPage }); 
    await Then('the LinkedBusinesses Permission Description table updates with the following descriptions \'View entitlements, Transfer entitlements, Apply for new entitlements\'', null, { contactsLinkedBusinessesPage }); 
  });

  test('Searching for a partially matching string in the Name column filters correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'1103020285\'', null, { page }); 
    await And('I am on the Contacts Linked Businesses page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'Bailey\' in the search box', null, { page }); 
    await Then('I see the the correct list of businesses as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"SBI"},{"value":"121428499"}]},{"cells":[{"value":"Name"},{"value":"\"Bailey, Dickens and Mraz\""}]}]}}, { contactsLinkedBusinessesPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of businesses as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"SBI"},{"value":"121428499, 106238988, 106284736, 107591843"}]},{"cells":[{"value":"Name"},{"value":"\"Bailey, Dickens and Mraz\", \"Gleichner,Okuneva and Murazik\", \"Goldner, Schmeler and Kutch\", \"Homenick, McDermott and Luettgen\""}]}]}}, { contactsLinkedBusinessesPage }); 
  });

  test('Searching for a partially matching string in the SBI column filters correctly', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'1103020285\'', null, { page }); 
    await And('I am on the Contacts Linked Businesses page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await When('I enter \'10759\' in the search box', null, { page }); 
    await Then('I see the the correct list of businesses as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"SBI"},{"value":"107591843"}]},{"cells":[{"value":"Name"},{"value":"\"Homenick, McDermott and Luettgen\""}]}]}}, { contactsLinkedBusinessesPage }); 
    await When('I enter a blank value in the search box', null, { page }); 
    await And('Press the Enter key', null, { page }); 
    await Then('I see the the correct list of businesses as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"SBI"},{"value":"121428499, 106238988, 106284736, 107591843"}]},{"cells":[{"value":"Name"},{"value":"\"Bailey, Dickens and Mraz\", \"Gleichner,Okuneva and Murazik\", \"Goldner, Schmeler and Kutch\", \"Homenick, McDermott and Luettgen\""}]}]}}, { contactsLinkedBusinessesPage }); 
  });

  test('Clicking the View Business button navigates the user to the relevant Business page in CRM.', { tag: ['@intermediate', '@data-dependent'] }, async ({ Given, When, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'1103020285\'', null, { page }); 
    await And('I am on the Contacts Linked Businesses page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await And('I have selected \'Homenick, McDermott and Luettgen\' in the Businesses table', null, { contactsLinkedBusinessesPage }); 
    await When('I click the View Business button', null, { contactsLinkedBusinessesPage }); 
    await Then('I see the CRM Organisation Details page for the \'Homenick, McDermott and Luettgen\' organisation', null, { contactsLinkedBusinessesPage }); 
  });

  test('The correct Linked Businesses are shown for a contact', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, Then, And, businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'1103020285\'', null, { page }); 
    await And('I am on the Contacts Linked Businesses page', null, { businessAgreementDetailsPage, businessAgreementsPage, businessApplicationsPage, businessCphDetailsPage, businessLandDetailsPage, businessLinkedContactsPage, businessMessagingPage, contactsAuthenticationPage, contactsLinkedBusinessesPage, page }); 
    await Then('I see the the correct list of businesses as follows', {"dataTable":{"rows":[{"cells":[{"value":"label"},{"value":"value"}]},{"cells":[{"value":"SBI"},{"value":"121428499, 106238988, 106284736, 107591843"}]},{"cells":[{"value":"Name"},{"value":"\"Bailey, Dickens and Mraz\", \"Gleichner,Okuneva and Murazik\", \"Goldner, Schmeler and Kutch\", \"Homenick, McDermott and Luettgen\""}]}]}}, { contactsLinkedBusinessesPage }); 
  });

  test('When a business\'s permission is NOT level "NO_ACCESS", the Permission Description list is correct.', { tag: ['@advanced', '@data-dependent'] }, async ({ Given, When, Then, And, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'1103020285\'', null, { page }); 
    await When('I select \'Homenick, McDermott and Luettgen\' in the Businesses table', null, { contactsLinkedBusinessesPage }); 
    await And('I select the Permission \'BASIC_PAYMENT_SCHEME\' from the Permissions table', null, { contactsLinkedBusinessesPage }); 
    await Then('the LinkedBusinesses Permission Description table updates with the following descriptions \'View business summary, View claims, "View land, features and covers", Create and edit a claim, Amend a previously submitted claim, "Amend land, features and covers", Submit a claim, Withdraw a claim, "Receive warnings and notifications"\'', null, { contactsLinkedBusinessesPage }); 
  });

  test('When a business\'s permission is level "NO_ACCESS", the Permission Description list shows the correct warning message "We didn\'t find any data to show at this time".', { tag: ['@advanced', '@data-dependent', '@require-mock-update'] }, async ({ Given, When, Then, And, contactsLinkedBusinessesPage, page }) => { 
    await Given('I have selected the contact with CRN \'0000000001\'', null, { page }); 
    await When('I select \'Homenick, McDermott and Luettgen\' in the Businesses table', null, { contactsLinkedBusinessesPage }); 
    await And('I select the Permission \'LAND_DETAILS\' from the Permissions table', null, { contactsLinkedBusinessesPage }); 
    await Then('I see the \'Permission Description\' table is empty', null, { page }); 
    await And('I see a warning message \'We didn\'t find any data to show at this time\' under the \'Permission Description\' table', null, { page }); 
  });

});

// == technical section ==

test.use({
  $test: [({}, use) => use(test), { scope: 'test', box: true }],
  $uri: [({}, use) => use('test/features/contacts-linked-businesses.feature'), { scope: 'test', box: true }],
  $bddFileData: [({}, use) => use(bddFileData), { scope: "test", box: true }],
});

const bddFileData = [ // bdd-data-start
  {"pwTestLine":6,"pickleLine":4,"tags":["@advanced","@data-dependent","@working"],"steps":[{"pwStepLine":7,"gherkinStepLine":5,"keywordType":"Context","textWithKeyword":"Given I have gone to the 'Contacts Linked Businesses' page","stepMatchArguments":[{"group":{"start":20,"value":"Contacts Linked Businesses","children":[]}}]},{"pwStepLine":8,"gherkinStepLine":6,"keywordType":"Context","textWithKeyword":"And I have selected the contact with CRN '9000000000'","stepMatchArguments":[{"group":{"start":38,"value":"9000000000","children":[]}}]},{"pwStepLine":9,"gherkinStepLine":7,"keywordType":"Outcome","textWithKeyword":"Then I see the 'Businesses' table is empty","stepMatchArguments":[{"group":{"start":11,"value":"Businesses","children":[]}}]}]},
  {"pwTestLine":12,"pickleLine":10,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":13,"gherkinStepLine":11,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '1103020285'","stepMatchArguments":[{"group":{"start":38,"value":"1103020285","children":[]}}]},{"pwStepLine":14,"gherkinStepLine":12,"keywordType":"Context","textWithKeyword":"And I am on the Contacts Linked Businesses page","stepMatchArguments":[{"group":{"start":12,"value":"Contacts Linked Businesses","children":[]}}]},{"pwStepLine":15,"gherkinStepLine":13,"keywordType":"Action","textWithKeyword":"When I select the business 'Bailey, Dickens and Mraz' from the Businesses table","stepMatchArguments":[{"group":{"start":23,"value":"Bailey, Dickens and Mraz","children":[]}}]},{"pwStepLine":16,"gherkinStepLine":14,"keywordType":"Outcome","textWithKeyword":"Then the LinkedBusinesses page updates to show the following information","stepMatchArguments":[]}]},
  {"pwTestLine":19,"pickleLine":24,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":20,"gherkinStepLine":25,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '1103020285'","stepMatchArguments":[{"group":{"start":38,"value":"1103020285","children":[]}}]},{"pwStepLine":21,"gherkinStepLine":26,"keywordType":"Context","textWithKeyword":"And I am on the Contacts Linked Businesses page","stepMatchArguments":[{"group":{"start":12,"value":"Contacts Linked Businesses","children":[]}}]},{"pwStepLine":22,"gherkinStepLine":27,"keywordType":"Action","textWithKeyword":"When I select the business 'Goldner, Schmeler and Kutch' from the Businesses table","stepMatchArguments":[{"group":{"start":23,"value":"Goldner, Schmeler and Kutch","children":[]}}]},{"pwStepLine":23,"gherkinStepLine":28,"keywordType":"Action","textWithKeyword":"And I select the Permission 'ENTITLEMENTS' from the Permissions table","stepMatchArguments":[{"group":{"start":25,"value":"ENTITLEMENTS","children":[]}}]},{"pwStepLine":24,"gherkinStepLine":29,"keywordType":"Outcome","textWithKeyword":"Then the LinkedBusinesses Permission Description table updates with the following descriptions 'View entitlements, Transfer entitlements, Apply for new entitlements'","stepMatchArguments":[{"group":{"start":91,"value":"View entitlements, Transfer entitlements, Apply for new entitlements","children":[]}}]}]},
  {"pwTestLine":27,"pickleLine":32,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":28,"gherkinStepLine":33,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '1103020285'","stepMatchArguments":[{"group":{"start":38,"value":"1103020285","children":[]}}]},{"pwStepLine":29,"gherkinStepLine":34,"keywordType":"Context","textWithKeyword":"And I am on the Contacts Linked Businesses page","stepMatchArguments":[{"group":{"start":12,"value":"Contacts Linked Businesses","children":[]}}]},{"pwStepLine":30,"gherkinStepLine":35,"keywordType":"Action","textWithKeyword":"When I enter 'Bailey' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"Bailey","children":[]}}]},{"pwStepLine":31,"gherkinStepLine":36,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of businesses as follows","stepMatchArguments":[]},{"pwStepLine":32,"gherkinStepLine":40,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":33,"gherkinStepLine":41,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":34,"gherkinStepLine":42,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of businesses as follows","stepMatchArguments":[]}]},
  {"pwTestLine":37,"pickleLine":48,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":38,"gherkinStepLine":49,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '1103020285'","stepMatchArguments":[{"group":{"start":38,"value":"1103020285","children":[]}}]},{"pwStepLine":39,"gherkinStepLine":50,"keywordType":"Context","textWithKeyword":"And I am on the Contacts Linked Businesses page","stepMatchArguments":[{"group":{"start":12,"value":"Contacts Linked Businesses","children":[]}}]},{"pwStepLine":40,"gherkinStepLine":51,"keywordType":"Action","textWithKeyword":"When I enter '10759' in the search box","stepMatchArguments":[{"group":{"start":9,"value":"10759","children":[]}}]},{"pwStepLine":41,"gherkinStepLine":52,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of businesses as follows","stepMatchArguments":[]},{"pwStepLine":42,"gherkinStepLine":56,"keywordType":"Action","textWithKeyword":"When I enter a blank value in the search box","stepMatchArguments":[]},{"pwStepLine":43,"gherkinStepLine":57,"keywordType":"Action","textWithKeyword":"And Press the Enter key","stepMatchArguments":[]},{"pwStepLine":44,"gherkinStepLine":58,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of businesses as follows","stepMatchArguments":[]}]},
  {"pwTestLine":47,"pickleLine":64,"tags":["@intermediate","@data-dependent"],"steps":[{"pwStepLine":48,"gherkinStepLine":65,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '1103020285'","stepMatchArguments":[{"group":{"start":38,"value":"1103020285","children":[]}}]},{"pwStepLine":49,"gherkinStepLine":66,"keywordType":"Context","textWithKeyword":"And I am on the Contacts Linked Businesses page","stepMatchArguments":[{"group":{"start":12,"value":"Contacts Linked Businesses","children":[]}}]},{"pwStepLine":50,"gherkinStepLine":67,"keywordType":"Context","textWithKeyword":"And I have selected 'Homenick, McDermott and Luettgen' in the Businesses table","stepMatchArguments":[{"group":{"start":17,"value":"Homenick, McDermott and Luettgen","children":[]}}]},{"pwStepLine":51,"gherkinStepLine":68,"keywordType":"Action","textWithKeyword":"When I click the View Business button","stepMatchArguments":[]},{"pwStepLine":52,"gherkinStepLine":69,"keywordType":"Outcome","textWithKeyword":"Then I see the CRM Organisation Details page for the 'Homenick, McDermott and Luettgen' organisation","stepMatchArguments":[{"group":{"start":49,"value":"Homenick, McDermott and Luettgen","children":[]}}]}]},
  {"pwTestLine":55,"pickleLine":72,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":56,"gherkinStepLine":73,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '1103020285'","stepMatchArguments":[{"group":{"start":38,"value":"1103020285","children":[]}}]},{"pwStepLine":57,"gherkinStepLine":74,"keywordType":"Context","textWithKeyword":"And I am on the Contacts Linked Businesses page","stepMatchArguments":[{"group":{"start":12,"value":"Contacts Linked Businesses","children":[]}}]},{"pwStepLine":58,"gherkinStepLine":75,"keywordType":"Outcome","textWithKeyword":"Then I see the the correct list of businesses as follows","stepMatchArguments":[]}]},
  {"pwTestLine":61,"pickleLine":81,"tags":["@advanced","@data-dependent"],"steps":[{"pwStepLine":62,"gherkinStepLine":82,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '1103020285'","stepMatchArguments":[{"group":{"start":38,"value":"1103020285","children":[]}}]},{"pwStepLine":63,"gherkinStepLine":83,"keywordType":"Action","textWithKeyword":"When I select 'Homenick, McDermott and Luettgen' in the Businesses table","stepMatchArguments":[{"group":{"start":9,"value":"'Homenick, McDermott and Luettgen'","children":[{"children":[{"children":[]}]},{"start":10,"value":"Homenick, McDermott and Luettgen","children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":64,"gherkinStepLine":84,"keywordType":"Action","textWithKeyword":"And I select the Permission 'BASIC_PAYMENT_SCHEME' from the Permissions table","stepMatchArguments":[{"group":{"start":25,"value":"BASIC_PAYMENT_SCHEME","children":[]}}]},{"pwStepLine":65,"gherkinStepLine":85,"keywordType":"Outcome","textWithKeyword":"Then the LinkedBusinesses Permission Description table updates with the following descriptions 'View business summary, View claims, \"View land, features and covers\", Create and edit a claim, Amend a previously submitted claim, \"Amend land, features and covers\", Submit a claim, Withdraw a claim, \"Receive warnings and notifications\"'","stepMatchArguments":[{"group":{"start":91,"value":"View business summary, View claims, \"View land, features and covers\", Create and edit a claim, Amend a previously submitted claim, \"Amend land, features and covers\", Submit a claim, Withdraw a claim, \"Receive warnings and notifications\"","children":[]}}]}]},
  {"pwTestLine":68,"pickleLine":88,"tags":["@advanced","@data-dependent","@require-mock-update"],"steps":[{"pwStepLine":69,"gherkinStepLine":89,"keywordType":"Context","textWithKeyword":"Given I have selected the contact with CRN '0000000001'","stepMatchArguments":[{"group":{"start":38,"value":"0000000001","children":[]}}]},{"pwStepLine":70,"gherkinStepLine":90,"keywordType":"Action","textWithKeyword":"When I select 'Homenick, McDermott and Luettgen' in the Businesses table","stepMatchArguments":[{"group":{"start":9,"value":"'Homenick, McDermott and Luettgen'","children":[{"children":[{"children":[]}]},{"start":10,"value":"Homenick, McDermott and Luettgen","children":[{"children":[]}]}]},"parameterTypeName":"string"}]},{"pwStepLine":71,"gherkinStepLine":91,"keywordType":"Action","textWithKeyword":"And I select the Permission 'LAND_DETAILS' from the Permissions table","stepMatchArguments":[{"group":{"start":25,"value":"LAND_DETAILS","children":[]}}]},{"pwStepLine":72,"gherkinStepLine":92,"keywordType":"Outcome","textWithKeyword":"Then I see the 'Permission Description' table is empty","stepMatchArguments":[{"group":{"start":11,"value":"Permission Description","children":[]}}]},{"pwStepLine":73,"gherkinStepLine":93,"keywordType":"Outcome","textWithKeyword":"And I see a warning message 'We didn't find any data to show at this time' under the 'Permission Description' table","stepMatchArguments":[{"group":{"start":25,"value":"We didn't find any data to show at this time","children":[]}},{"group":{"start":82,"value":"Permission Description","children":[]}}]}]},
]; // bdd-data-end